// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqZNR8tKAGZZpx0luvcSLuLkRIzLWZAGM',
    appId: '1:1093119944968:web:461c6e3d56f5ab8b7b64bd',
    messagingSenderId: '1093119944968',
    projectId: 'sport-venue-booking-app-2d06f',
    authDomain: 'sport-venue-booking-app-2d06f.firebaseapp.com',
    storageBucket: 'sport-venue-booking-app-2d06f.firebasestorage.app',
    measurementId: 'G-GZV4HZE2VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxBTErWmr9sw5FMNkkqmq4F2Z9RMKnoSM',
    appId: '1:1093119944968:android:0663f819fc1b91d27b64bd',
    messagingSenderId: '1093119944968',
    projectId: 'sport-venue-booking-app-2d06f',
    storageBucket: 'sport-venue-booking-app-2d06f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqS9FL2ZN3b0obcOYFriGPutYPllyCUbw',
    appId: '1:1093119944968:ios:7f790cd583c327cc7b64bd',
    messagingSenderId: '1093119944968',
    projectId: 'sport-venue-booking-app-2d06f',
    storageBucket: 'sport-venue-booking-app-2d06f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqS9FL2ZN3b0obcOYFriGPutYPllyCUbw',
    appId: '1:1093119944968:ios:7f790cd583c327cc7b64bd',
    messagingSenderId: '1093119944968',
    projectId: 'sport-venue-booking-app-2d06f',
    storageBucket: 'sport-venue-booking-app-2d06f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqZNR8tKAGZZpx0luvcSLuLkRIzLWZAGM',
    appId: '1:1093119944968:web:72d7b7e3adfdeaa37b64bd',
    messagingSenderId: '1093119944968',
    projectId: 'sport-venue-booking-app-2d06f',
    authDomain: 'sport-venue-booking-app-2d06f.firebaseapp.com',
    storageBucket: 'sport-venue-booking-app-2d06f.firebasestorage.app',
    measurementId: 'G-7MSDLCB7BK',
  );
}
